/**
 * Missouri Marketing (میسوری مارکیٹنگ)
 * Official Properties & Societies Database
 */

const PROPERTIES_DATA = [
  {
    id: "prop-01",
    title: "10 Marla Luxury Modern Spanish Villa",
    slug: "10-marla-luxury-modern-spanish-villa",
    type: "house",
    category: "Luxury Designer House",
    society: "Bahria Town Phase 8",
    city: "Rawalpindi / Islamabad",
    price: "PKR 3.45 Crore",
    priceRaw: 34500000,
    size: "10 Marla",
    marla: 10,
    dimensions: "35 x 70 Feet",
    installmentsAvailable: false,
    downPayment: "Full Cash / Bank Transfer",
    monthlyInstallment: "Ready for Immediate Living",
    duration: "Ready Possession",
    possession: "Immediate Possession",
    status: "For Sale",
    badge: "Super Luxury",
    beds: 5,
    baths: 6,
    kitchens: 2,
    carParking: "2 Luxury Cars",
    image: "assets/hero_luxury_villa.jpg",
    gallery: [
      "assets/hero_luxury_villa.jpg",
      "assets/house_interior.jpg",
      "assets/house_contemporary.jpg"
    ],
    nocStatus: "Approved by RDA & Bahria Management",
    features: [
      "Double Storey Contemporary Facade",
      "Spanish & Italian Tile Flooring",
      "Imported Grohe & Kohler Sanitary",
      "Solid Ash Wood Doors & Wardrobes",
      "Solar System 10kW Installed",
      "Servant Quarter with Attached Bath",
      "Lush Manicured Lawn & Rooftop BBQ Terrace"
    ],
    description: "Missouri Marketing exclusively presents this architectural masterpiece in Bahria Town Phase 8. Built with solid steel & grade-A cement, this 5-bed luxury house boasts double-height ceilings, designer chandeliers, imported kitchens with appliances, and zero compromises on luxury. Verified title deed with swift transfer at Bahria Head Office.",
    mapLocation: "Sector F, Street 18, Walking Distance to Commercial Hub & Grand Mosque",
    agent: "Adil Dawar",
    phone: "+92 300 5557890",
    featured: true
  },
  {
    id: "prop-02",
    title: "5 Marla Prime Residential Plot - Faisal Hills Block B",
    slug: "5-marla-prime-residential-plot-faisal-hills",
    type: "plot",
    category: "Residential Plot",
    society: "Faisal Hills (Taxila / Islamabad)",
    city: "Islamabad Sector Extension",
    price: "PKR 38.5 Lakhs",
    priceRaw: 3850000,
    size: "5 Marla",
    marla: 5,
    dimensions: "25 x 50 Feet",
    installmentsAvailable: true,
    downPayment: "PKR 850,000",
    monthlyInstallment: "PKR 45,000",
    duration: "2.5 Years Easy Installments",
    possession: "Balloted / On-Ground Ready",
    status: "Hot Deal",
    badge: "Best Investment",
    beds: null,
    baths: null,
    image: "assets/society_plots.jpg",
    gallery: [
      "assets/society_plots.jpg",
      "assets/plot_green.jpg"
    ],
    nocStatus: "100% Approved by RDA (Rawalpindi Development Authority)",
    features: [
      "Direct G.T Road & Motorway Access",
      "Underground Electricity & Gas Infrastructure",
      "Scenic Margalla Hills View",
      "Wide 40 Feet Paved Street",
      "Immediate Construction Permitted",
      "High Capital Appreciation Zone"
    ],
    description: "An exceptional chance to own a 5 Marla residential plot in the prestigious Faisal Hills Block B, marketed by Missouri Marketing. The block is fully developed with carpeted roads, functional sewerage, street lights, and thriving construction. Ideal for both short-term profit and building your dream family home.",
    mapLocation: "Block B, Street 9, Near Central Park & Educational Complex",
    agent: "Adil Dawar",
    phone: "+92 300 5557890",
    featured: true
  },
  {
    id: "prop-03",
    title: "1 Kanal Executive Golf Estate Plot - Park View City",
    slug: "1-kanal-executive-golf-estate-plot-park-view-city",
    type: "plot",
    category: "Residential Plot",
    society: "Park View City",
    city: "Zone IV Islamabad",
    price: "PKR 1.95 Crore",
    priceRaw: 19500000,
    size: "1 Kanal",
    marla: 20,
    dimensions: "50 x 90 Feet",
    installmentsAvailable: true,
    downPayment: "PKR 3,500,000",
    monthlyInstallment: "PKR 125,000",
    duration: "2 Years Flexible Plan",
    possession: "Possession Offered in 6 Months",
    status: "For Sale",
    badge: "Premium Boulevard",
    beds: null,
    baths: null,
    image: "assets/plot_green.jpg",
    gallery: [
      "assets/plot_green.jpg",
      "assets/society_plots.jpg"
    ],
    nocStatus: "CDA Approved Housing Project",
    features: [
      "Botanical Garden & Golf Course Adjacency",
      "100 Feet Main Boulevard Frontage",
      "Corner Option Available",
      "24/7 Gated Security & Smart Surveillance",
      "Load-shedding Free Dedicated Feeders",
      "15 Minutes Drive from Serena Hotel Islamabad"
    ],
    description: "Missouri Marketing brings you an exclusive 1 Kanal plot in the Golf Estate of Park View City Islamabad. Surrounded by the serene Margalla nature reserves, Park View City offers unparalleled status and tranquility. High yield potential with fast-paced CDA-backed development.",
    mapLocation: "Golf Estate Block, Plot # 142, Facing Natural Water Lake & Greens",
    agent: "Adil Dawar",
    phone: "+92 300 5557890",
    featured: true
  },
  {
    id: "prop-04",
    title: "5 Marla Brand New Modern House - B-17 Multi Gardens",
    slug: "5-marla-brand-new-modern-house-b17",
    type: "house",
    category: "Residential House",
    society: "B-17 Multi Gardens MPCHS",
    city: "Islamabad",
    price: "PKR 1.68 Crore",
    priceRaw: 16800000,
    size: "5 Marla",
    marla: 5,
    dimensions: "25 x 50 Feet",
    installmentsAvailable: false,
    downPayment: "Full Cash / Bank Financing",
    monthlyInstallment: "Ready to Move",
    duration: "Immediate Handover",
    possession: "Immediate Key Handover",
    status: "For Sale",
    badge: "Ready to Move",
    beds: 4,
    baths: 4,
    kitchens: 2,
    carParking: "1 Big SUV",
    image: "assets/house_contemporary.jpg",
    gallery: [
      "assets/house_contemporary.jpg",
      "assets/house_interior.jpg",
      "assets/hero_luxury_villa.jpg"
    ],
    nocStatus: "CDA & MPCHS Approved",
    features: [
      "Modern Minimalist Elevation",
      "Solid Kalat Marble & Imported Porcelain",
      "Two Separate Electric & Gas Meters",
      "Rooftop Pergola with Margalla Hills View",
      "Near Markaz & Commercial Market",
      "Complete Registry & Transfer Ready"
    ],
    description: "Built for comfortable family living or high rental return (approx PKR 70,000/month). Features 4 spacious en-suite bedrooms, dual modern open kitchens, drawing/dining hall, TV lounge, and rooftop access. Missouri Marketing guarantees clean documentation and fast legal transfer.",
    mapLocation: "Sector C-1, Multi Gardens B-17, Walking Distance to Zoo & Park",
    agent: "Adil Dawar",
    phone: "+92 300 5557890",
    featured: true
  },
  {
    id: "prop-05",
    title: "7 Marla Commercial Boulevard Plot - Blue World City",
    slug: "7-marla-commercial-boulevard-plot-blue-world-city",
    type: "commercial",
    category: "Commercial Plot",
    society: "Blue World City",
    city: "Rawalpindi Ring Road / Motorway",
    price: "PKR 54.0 Lakhs",
    priceRaw: 5400000,
    size: "7 Marla",
    marla: 7,
    dimensions: "30 x 55 Feet",
    installmentsAvailable: true,
    downPayment: "PKR 980,000",
    monthlyInstallment: "PKR 55,000",
    duration: "4 Years Easy Installment Plan",
    possession: "Possession with 50% Clear",
    status: "Hot Deal",
    badge: "High ROI",
    beds: null,
    baths: null,
    image: "assets/commercial_tower.jpg",
    gallery: [
      "assets/commercial_tower.jpg",
      "assets/society_plots.jpg"
    ],
    nocStatus: "NOC in Process / PHATA Approved Land",
    features: [
      "Direct Facing 120 Feet Main Boulevard",
      "Ideal for Multi-Storey Commercial Plaza / Shops",
      "Close to Pakistan's Biggest Water Theme Park",
      "Direct Connectivity to CPEC Route & Ring Road",
      "Rapidly Developing International Standard Project"
    ],
    description: "Missouri Marketing is an authorized partner offering prime commercial plots on Blue World City's bustling main avenues. Build retail outlets, corporate offices, or food franchises with remarkable return on investment. Flexible 4-year installment plan designed for overseas and smart local investors.",
    mapLocation: "General Block Commercial Avenue, Near Main Gateway",
    agent: "Adil Dawar",
    phone: "+92 300 5557890",
    featured: false
  },
  {
    id: "prop-06",
    title: "1 Kanal Designer Luxury House - DHA Islamabad Phase 2",
    slug: "1-kanal-designer-luxury-house-dha-islamabad",
    type: "house",
    category: "Luxury Designer House",
    society: "DHA Islamabad Phase 2",
    city: "Islamabad",
    price: "PKR 6.80 Crore",
    priceRaw: 68000000,
    size: "1 Kanal",
    marla: 20,
    dimensions: "50 x 90 Feet",
    installmentsAvailable: false,
    downPayment: "Direct Bank Transfer",
    monthlyInstallment: "Turnkey Possession",
    duration: "Ready Possession",
    possession: "Immediate Possession",
    status: "For Sale",
    badge: "Elite Mansion",
    beds: 6,
    baths: 7,
    kitchens: 3,
    carParking: "4 Vehicles Space",
    image: "assets/house_spanish.jpg",
    gallery: [
      "assets/house_spanish.jpg",
      "assets/house_interior.jpg",
      "assets/hero_luxury_villa.jpg"
    ],
    nocStatus: "DHA Islamabad Official Transfer",
    features: [
      "Architecturally Designed by Top Renowned Firm",
      "Private Swimming Pool / Jacuzzi Provision",
      "Full Smart Home Automation & Security Cameras",
      "Italian Imported Designer Kitchen with Island",
      "Basement Home Cinema / Entertainment Lounge",
      "Veneered Oak Woodwork & High Ceilings"
    ],
    description: "The epitome of high-class prestige in DHA Phase 2 Islamabad. Featuring 6 master suites, high-tech automation, bespoke imported chandeliers, triple-glazed windows, and pristine lawn. Adil Dawar personally oversees the complete transaction ensuring 100% legal safety and discreet luxury service.",
    mapLocation: "Sector J, Prime Street, DHA Phase 2 Islamabad",
    agent: "Adil Dawar",
    phone: "+92 300 5557890",
    featured: true
  },
  {
    id: "prop-07",
    title: "10 Marla Residential Plot - New Metro City Gujar Khan",
    slug: "10-marla-residential-plot-new-metro-city",
    type: "plot",
    category: "Residential Plot",
    society: "New Metro City Gujar Khan",
    city: "G.T Road Rawalpindi District",
    price: "PKR 31.5 Lakhs",
    priceRaw: 3150000,
    size: "10 Marla",
    marla: 10,
    dimensions: "35 x 70 Feet",
    installmentsAvailable: true,
    downPayment: "PKR 550,000",
    monthlyInstallment: "PKR 32,500",
    duration: "3 Years Installments",
    possession: "Early Possession Announced",
    status: "For Sale",
    badge: "Easy Installments",
    beds: null,
    baths: null,
    image: "assets/society_plots.jpg",
    gallery: [
      "assets/society_plots.jpg",
      "assets/plot_green.jpg"
    ],
    nocStatus: "TMA & District Approved",
    features: [
      "BSM Developers Quality Execution",
      "Direct Main G.T Road Location",
      "Underground Electrification & Gated Security",
      "Glow Park, Theme Park & Miracle Garden",
      "High Appreciation for Overseas Remittances"
    ],
    description: "Missouri Marketing brings the most affordable 10 Marla plot with rapid on-ground development in New Metro City Gujar Khan. Excellent road connectivity to Rawalpindi/Islamabad and Jhelum. Low entry cost with flexible quarterly and monthly schedules.",
    mapLocation: "Block A Prime, Plot # 308, Near Central Commercial Ring",
    agent: "Adil Dawar",
    phone: "+92 300 5557890",
    featured: false
  },
  {
    id: "prop-08",
    title: "4 Kanal Resort Style Luxury Farmhouse - Gulberg Greens",
    slug: "4-kanal-resort-style-luxury-farmhouse-gulberg",
    type: "farmhouse",
    category: "Luxury Farmhouse",
    society: "Gulberg Greens Islamabad",
    city: "Islamabad Expressway",
    price: "PKR 12.5 Crore",
    priceRaw: 125000000,
    size: "4 Kanal",
    marla: 80,
    dimensions: "180 x 200 Feet",
    installmentsAvailable: false,
    downPayment: "Full Cash / Token Deal",
    monthlyInstallment: "Ready for Luxurious Living",
    duration: "Ready Possession",
    possession: "Immediate Handover",
    status: "For Sale",
    badge: "Ultra Luxury",
    beds: 5,
    baths: 6,
    kitchens: 2,
    carParking: "6+ Cars Inside",
    image: "assets/farmhouse.jpg",
    gallery: [
      "assets/farmhouse.jpg",
      "assets/hero_luxury_villa.jpg",
      "assets/house_interior.jpg"
    ],
    nocStatus: "IBECHS & CDA Approved Society",
    features: [
      "4 Kanal Lush Organic Orchards & Green Lawns",
      "Modern Single-Storey Country Villa",
      "Private Swimming Pool & Gazebo",
      "Equipped with Generator & Solar Backup",
      "Dedicated Guard Room & Horse Stable / Kennel Space",
      "Direct 10-Minute Access to Zero Point Islamabad"
    ],
    description: "Live like royalty inside Gulberg Greens Islamabad. An exclusive farm estate surrounded by exotic flora, fruit orchards, and contemporary architecture. Ideal for dignitaries, top executives, and overseas investors seeking luxury living in Islamabad.",
    mapLocation: "Executive Block, Jasmine Lane, Gulberg Greens Islamabad",
    agent: "Adil Dawar",
    phone: "+92 300 5557890",
    featured: false
  }
];

const SOCIETIES_DATA = [
  {
    id: "soc-1",
    name: "Faisal Hills & Faisal Town",
    tagline: "Zedem International - Proven Delivery & Fast Possession",
    location: "Main G.T Road, Taxila / Islamabad Margalla View",
    noc: "RDA Approved",
    statusBadge: "Active Construction",
    image: "assets/society_plots.jpg",
    minPrice: "PKR 35 Lakhs",
    categories: ["5 Marla Plots", "8 Marla Plots", "10 Marla Plots", "1 Kanal Plots", "Commercial"],
    description: "Known for rapid development, wide carpeted roads, Margalla foothills ambiance, and trustworthy Zedem International leadership. The best choice for immediate home construction."
  },
  {
    id: "soc-2",
    name: "Park View City Islamabad",
    tagline: "Vision Group - CDA Approved Luxury Living in Zone IV",
    location: "Malot Road, Near Bahria Enclave, Islamabad",
    noc: "CDA Approved",
    statusBadge: "Rapid Handover",
    image: "assets/plot_green.jpg",
    minPrice: "PKR 55 Lakhs",
    categories: ["Golf Estate", "Downtown Commercial", "Overseas Block", "Hills Estate"],
    description: "Surrounded by nature, modern botanical gardens, and 200-ft main boulevards. Close to Serena Hotel Islamabad, offering highest prestige and rental yields."
  },
  {
    id: "soc-3",
    name: "Blue World City Islamabad",
    tagline: "Blue Group of Companies & BGF - World Class Tourist City",
    location: "Chakri Road, Near Rawalpindi Ring Road & Motorway M-2",
    noc: "Approved / Processing",
    statusBadge: "Mega Masterplan",
    image: "assets/commercial_tower.jpg",
    minPrice: "PKR 14 Lakhs",
    categories: ["General Block", "Overseas Block", "Waterfront", "Shoe & Sports City"],
    description: "Pakistan's landmark tourism community featuring replicas of Burj Al Arab, Blue Mosque, and world-class theme parks. Highly flexible 4-year installment plans."
  },
  {
    id: "soc-4",
    name: "Multi Gardens B-17 MPCHS",
    tagline: "Multi Professional Cooperative Housing Society",
    location: "Sector B-17, Main G.T Road & M-1 Motorway Interchange",
    noc: "CDA Approved",
    statusBadge: "Fully Inhabited",
    image: "assets/house_contemporary.jpg",
    minPrice: "PKR 45 Lakhs",
    categories: ["Block A to G", "Multi Zoo & Lake", "Commercial Markaz"],
    description: "A bustling, fully developed sector of Islamabad with thousands of families already residing. Complete gas, electricity, schools, hospitals, and parks."
  },
  {
    id: "soc-5",
    name: "Bahria Town & DHA Islamabad",
    tagline: "The Pinnacle of Secure Gated Community Living",
    location: "Phase 1 - 8 Rawalpindi / Islamabad Expressway",
    noc: "Officially Certified",
    statusBadge: "Ready Possession",
    image: "assets/hero_luxury_villa.jpg",
    minPrice: "PKR 90 Lakhs",
    categories: ["Luxury Villas", "Commercial Plazas", "Apartment Suites"],
    description: "The gold standard of real estate in Pakistan. Uninterrupted power supply, private security, hospitals, golf clubs, and high-end retail hubs."
  }
];

const TESTIMONIALS_DATA = [
  {
    name: "Chaudhry Kamran Tariq",
    location: "Manchester, United Kingdom",
    role: "Overseas Pakistani Investor",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    quote: "Being in the UK, buying property in Pakistan was always risky for me due to fraud fears. Adil Dawar and Missouri Marketing took complete charge, showed live on-ground drone videos of my Faisal Hills plot, and got the file transferred smoothly in my name. 100% trustworthy and professional!"
  },
  {
    name: "Engr. Zahid Mehmood",
    location: "Islamabad, Pakistan",
    role: "Homeowner in Bahria Town",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    quote: "Missouri Marketing helped me purchase our dream 10 Marla designer house. Adil Dawar personally inspected the construction quality, grey structure, and sewerage lines before advising us. Their transparent pricing saved us over 15 Lakh rupees!"
  },
  {
    name: "Farhan & Dr. Ayesha Siddiqui",
    location: "Dubai, United Arab Emirates",
    role: "Commercial Property Investors",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    quote: "We booked 2 commercial boulevard plots through Missouri Marketing on installments. The ROI within 18 months has been over 40%! Adil Dawar is a man of his word. Highly recommended for genuine investors."
  }
];

// Missouri Marketing Company details
const COMPANY_INFO = {
  name: "Missouri Marketing",
  urduName: "میسوری مارکیٹنگ",
  taglineUrdu: "آپ کی خدمت کے لیے ہمہ وقت کوشاں",
  taglineEn: "Always Striving to Serve You with Trust & Transparency",
  founder: "Adil Dawar",
  founderTitle: "Founder & Chief Executive Officer",
  phone: "+92 300 5557890",
  whatsapp: "+923005557890",
  email: "info@missourimarketing.com",
  officeAddress: "Missouri Marketing Executive Plaza, Main Boulevard, Faisal Hills / Islamabad, Pakistan",
  workingHours: "Mon - Sat: 9:00 AM - 9:00 PM | Sun: Site Visits by Appointment"
};
